nb:
	notedown 00_introduction.md > 00_introduction.ipynb

slides:
	jupyter nbconvert 00_introduction.ipynb --to slides --post serve \n--SlidesExporter.reveal_theme=serif \n--SlidesExporter.reveal_scroll=True \n--SlidesExporter.reveal_transition=none
